declare(q, scalar)$
declare(L, scalar)$

for i:1 thru 6 do (
    eval_string(coseno(i)),
    eval_string(seno(i))
)$

for i: 1 thru 6 do (
    for j: 1 thru 6 do (
        eval_string(coseno2(i, j)),
        eval_string(seno2(i, j))
    )
)$

for i: 1 thru 6 do (
    for j: 1 thru 6 do (
        for k: 1 thru 6 do (
            eval_string(coseno3(i, j, k)),
            eval_string(seno3(i, j, k))
        )
    )
)$

polsosferico: matrix(
    [q[4], L[3], %pi/2, 0],
    [q[5], 0, -%pi/2, 0],
    [q[6], L[4], 0, 0]
)$
dh : denavit_hartenberg(polsosferico);

d36 : transpose(matrix([0, 0, 0]))$
for i: 1 thru 3 do (
    d36[i] : [dh[i][4]]
)$

R36 : ident(3)$
for i: 1 thru 3 do (
    for j: 1 thru 3 do (
        R36[i][j] : dh[i][j]
    )
)$

d0 : transpose(matrix([d0a, d0b, d0c]))$
d1 : transpose(matrix([d1a, d1b, d1c]))$

eq : d36 = letsimp(R36).d1+d0$

antropomorfo: matrix(
    [q[1], L[1], -%pi/2, 0],
    [q[2], 0, 0, L[2]],
    [q[3], 0, -%pi/2, 0]
)$
dh : denavit_hartenberg(antropomorfo);

d03 : transpose(matrix([0, 0, 0]))$
for i: 1 thru 3 do (
    d03[i] : [dh[i][4]]
)$

R03 : ident(3)$
for i: 1 thru 3 do (
    for j: 1 thru 3 do (
        R03[i][j] : dh[i][j]
    )
)$

d0 : transpose(matrix([0, 0, L[4]]));
d1 : transpose(matrix([0, 0, L[3]]));
d : transpose(matrix([a, b, c]));
R : matrix(
    [r[11], r[12], r[13]],
    [r[21], r[22], r[23]],
    [r[31], r[32], r[33]]
);

sist_eq_1 : letsimp(R03) . d0 + letsimp(d03) = d - R . d1$
sist_eq_2 : R36 = transpose(letsimp(R03)) . R$

print(letsimp(eq))$
print(letsimp(d03))$
print(letsimp(R03))$
print(letsimp(d36))$
print(letsimp(R36))$
print(letsimp(d))$
print(letsimp(R))$
print(letsimp(sist_eq_1))$
print(letsimp(sist_eq_2))$
