declare(q, scalar)$
declare(L, scalar)$

antropomorfo : matrix(
    [q[1], L[1], -%pi/2, 0, [0, L[1]/2, 0]],
    [q[2], 0, 0, L[2], [-L[2]/2, 0, 0]],
    [q[3], 0, 0, L[3], [-L[3]/2, 0, 0]]
)$
test_calcolo_energia_cinetica(antropomorfo)$

polsosferico : matrix(
    [q[1], L[1], -%pi/2, 0, [0, -L[1]/2, 0]],
    [q[2], 0, -%pi/2, 0, [0, 0, 0]],
    [q[3], L[2], 0, 0, [0, 0, -L[2]/2]]
)$
test_calcolo_energia_cinetica(polsosferico)$

cilindrico : matrix(
    [q[1], L[1], 0, 0, [0, 0, L[1]/2]],
    [0, q[2], -%pi/2, 0, [0, L[2]/2, 0]],
    [0, q[3], 0, 0, [0, 0, -L[3]/2]]
)$
test_calcolo_energia_cinetica(cilindrico)$

sfericostanford : matrix(
    [q[1], L[1], -%pi/2, 0, [0, L[1]/2, 0]],
    [q[2], L[2], %pi/2, 0, [0, -L[2]/2, 0]],
    [0, q[3], 0, 0, [0, 0, -L[3]/2]]
)$
test_calcolo_energia_cinetica(sfericostanford)$

cartesiano : matrix(
    [0, q[1], -%pi/2, 0, [0, L[1]/2, 0]],
    [-%pi/2, q[2], -%pi/2, 0, [0, L[2]/2, 0]],
    [0, q[3], 0, 0, [0, 0, -L[3]/2]]
)$
test_calcolo_energia_cinetica(cartesiano)$
